name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SynapseTools.sln

      - name: Build solution
        run: msbuild SynapseTools.sln -t:rebuild -verbosity:diag -property:Configuration=Release

      - name: Run Tests
        run: vstest.console.exe .\SynapseToolsTests\bin\Release\SynapseToolsTests.dll

      - name: Run tests
        uses: microsoft/vstest@v1
        with:
          testAssembly: SynapseToolsTests.dll